# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение датчиков
GET {{baseUrl}}/sensors/
Content-Type: application/json

###

# создание датчика
POST {{baseUrl}}/sensors/
Content-Type: application/json

{
  "name": "ESP21",
  "description": "Датчик в комнате"
}

###

# обновление датчика
PATCH {{baseUrl}}/sensors/10/
Content-Type: application/json

{
  "description": "Перенес датчик на веранду"
}

###

# добавление измерения
POST {{baseUrl}}/measurements/
Content-Type: application/json

{
  "sensor": 7,
  "temperature": 20.4,
  "photo": "/Images/None/sensor_1.jpg"
}

###

# получение информации по датчику
GET {{baseUrl}}/sensors/7/
Content-Type: application/json
